### ISSUE TITLE
Problem about running the code

### ISSUE THREAD

**Issue by WangJuan6** [joel99/objectnav#7]
## ❓ Questions and Help
Hi Joel:
    My environment configuration is Python 3.6, Habitat Lab v0.1.5, and Habitat Sim v0.1.6 (headless). 
    When I set run-type as eval, the code works, but when I set run-type as train, there is an error:

```
Traceback (most recent call last):
  File "/home/wj/projects/objectnav/habitat_baselines/run_path.py", line 407, in <module>
    main()
  File "/home/wj/projects/objectnav/habitat_baselines/run_path.py", line 134, in main
    run_exp(**vars(args))
  File "/home/wj/projects/objectnav/habitat_baselines/run_path.py", line 312, in run_exp
    trainer.train(ckpt_path=ckpt_path, ckpt=ckpt, start_updates=start_updates)
  File "/home/wj/projects/objectnav/habitat_baselines/rl/ppo/belief_ddppo_trainer.py", line 97, in train
    self.config, get_env_class(self.config.ENV_NAME)
  File "/home/wj/projects/objectnav/habitat_baselines/common/env_utils.py", line 109, in construct_envs
    workers_ignore_signals=workers_ignore_signals,
  File "/home/wj/projects/objectnav/habitat/core/vector_env.py", line 146, in __init__
    read_fn() for read_fn in self._connection_read_fns
  File "/home/wj/projects/objectnav/habitat/core/vector_env.py", line 146, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/wj/anaconda3/envs/aux/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/wj/anaconda3/envs/aux/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/wj/anaconda3/envs/aux/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <bound method VectorEnv.__del__ of <habitat.core.vector_env.VectorEnv object at 0x7f96c8fa1b00>>
Traceback (most recent call last):
  File "/home/wj/projects/objectnav/habitat/core/vector_env.py", line 534, in __del__
    self.close()
  File "/home/wj/projects/objectnav/habitat/core/vector_env.py", line 416, in close
    write_fn((CLOSE_COMMAND, None))
  File "/home/wj/anaconda3/envs/aux/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/wj/anaconda3/envs/aux/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/wj/anaconda3/envs/aux/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

Can you help me to solve this problem?
Thanks,
Juan

**Comment by kevin-xuan** [comment]
I also encountered a similar error. How to solve this problem?
[Errno` 104] Connection reset by peer
  File "/home/raoxuan/code/objectnav/habitat/core/vector_env.py", line 146, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/raoxuan/code/objectnav/habitat/core/vector_env.py", line 145, in __init__
    self.observation_spaces = [
  File "/home/raoxuan/code/objectnav/habitat_baselines/common/env_utils.py", line 106, in construct_envs
    envs = habitat.VectorEnv(
  File "/home/raoxuan/code/objectnav/habitat_baselines/rl/ppo/belief_ddppo_trainer.py", line 96, in train
    self.envs = construct_envs(
  File "/home/raoxuan/code/objectnav/habitat_baselines/run.py", line 325, in run_exp
    trainer.train()
  File "/home/raoxuan/code/objectnav/habitat_baselines/run.py", line 136, in main
    run_exp(**vars(args))
  File "/home/raoxuan/code/objectnav/habitat_baselines/run.py", line 409, in <module>
    main()

**Comment by kevin-xuan** [comment]
OK, you need to download the scene datasets, and put the mp3d_habitat.zip into the ./data/scene_datasets and then unzip the file. As for the scene_config file, just follow the corresponding instructions.

**Comment by kevin-xuan** [comment]
But I encounter  another problem. The code works fine at first, but the following error occurs after 150 updates:
![捕获3](https://user-images.githubusercontent.com/87954969/192142015-fe6b8a6a-4370-4afc-ac07-6e77487bd01e.PNG)
![捕获2](https://user-images.githubusercontent.com/87954969/192142019-fff601d2-61e8-43d5-a953-fc10e22ac9c7.PNG)
It doesn't seem to load a particular scene datasets properly. Could I get some help?

**Comment by kevin-xuan** [comment]
Sorry, this seems to be a download issue, the code works fine when i re-download the scene datasets.

**Comment by joel99** [comment]
I apologize for leaving this unattended, but I also no longer have access to the datasets here. I will note the OP's logs are a generic crash log, and they might want to look earlier than the screenshot for something more informative.
